// <auto-generated />
using Dev;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dev.Migrations
{
    [DbContext(typeof(PgContent))]
    [Migration("20260505203917_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Dev.Entities.ContentBuilding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Dynasties")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Img")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Meta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Navigation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("true");

                    b.Property<string>("Path")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Provinces")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Stem")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Subtitle")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("_content_buildings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
