// <auto-generated />
using System;
using System.Text.Json;
using Buildings.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Buildings.Migrations
{
    [DbContext(typeof(BuildingDbContext))]
    [Migration("20260511131239_RemakeComments")]
    partial class RemakeComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Account.FriendRelationInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ActionUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("FriendId")
                        .HasColumnType("bigint");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_FriendRelationInfo_Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FriendRelationInfo_CreatedAt");

                    b.HasIndex("FriendId", "Status")
                        .HasDatabaseName("IX_FriendRelationInfo_FriendId_Status");

                    b.HasIndex("UserId", "FriendId")
                        .IsUnique()
                        .HasDatabaseName("IX_FriendRelationInfo_IdPair");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_FriendRelationInfo_UserId_Status");

                    b.ToTable("FriendRelationInfo", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Account.UserAccountInfo", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.PrimitiveCollection<string>("Interest")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId")
                        .HasName("PK_UserAccountInfo_UserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UserAccountInfo_CreatedAt");

                    b.HasIndex("Interest")
                        .HasDatabaseName("IX_UserAccountInfo_Interest");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Interest"), "GIN");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_UserAccountInfo_UpdateAt");

                    b.HasIndex("UserName", "DeleteAt")
                        .HasDatabaseName("IX_UserAccountInfo_UserName");

                    b.ToTable("UserAccountInfo", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.BuildingArticleData", b =>
                {
                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dynasties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provinces")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Seo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArticleId")
                        .HasName("PK_BuildingArticleData_ArticleId");

                    b.HasIndex("Categories")
                        .HasDatabaseName("IX_BuildingArticleData_Categories");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Categories"), "GIN");

                    b.HasIndex("Dynasties")
                        .HasDatabaseName("IX_BuildingArticleData_Dynasties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Dynasties"), "GIN");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_BuildingArticleData_Hash");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("IX_BuildingArticleData_Path");

                    b.HasIndex("Provinces")
                        .HasDatabaseName("IX_BuildingArticleData_Provinces");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Provinces"), "GIN");

                    b.ToTable("BuildingArticleData", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Forum.BlogComment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("RootId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_BlogComment_CommentId");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_BlogComment_AuthorId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_BlogComment_CreatedAt");

                    b.HasIndex("IsAi")
                        .HasDatabaseName("IX_BlogComment_IsAi");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_BlogComment_PostId");

                    b.HasIndex("RootId")
                        .HasDatabaseName("IX_BlogComment_RootId");

                    b.ToTable("BlogComment", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Forum.BlogPost", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_BlogPost_PostId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_BlogPost_CreatedAt");

                    b.HasIndex("IsAi")
                        .HasDatabaseName("IX_BlogPost_IsAi");

                    b.HasIndex("Tag")
                        .HasDatabaseName("IX_BlogPost_Tag");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_BlogPost_UpdateAt");

                    b.ToTable("BlogPost", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Secure.UserSecureInfo", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordSaltHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId")
                        .HasName("PK_UserSecureInfo_UserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UserSecureInfo_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_UserSecureInfo_UpdateAt");

                    b.HasIndex("Email", "DeleteAt")
                        .IsUnique()
                        .HasDatabaseName("IX_UserSecureInfo_Email");

                    b.ToTable("UserSecureInfo", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Secure.UserSecureToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAcquired")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Hash")
                        .HasName("PK_UserSecureToken_UserId");

                    b.ToTable("UserSecureToken", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Account.FriendRelationInfo", b =>
                {
                    b.HasOne("Buildings.Infrastructure.Data.Entities.Account.UserAccountInfo", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Buildings.Infrastructure.Data.Entities.Account.UserAccountInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Forum.BlogComment", b =>
                {
                    b.HasOne("Buildings.Infrastructure.Data.Entities.Account.UserAccountInfo", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Buildings.Infrastructure.Data.Entities.Forum.BlogComment", null)
                        .WithMany("ChildComments")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Buildings.Infrastructure.Data.Entities.Forum.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Forum.BlogPost", b =>
                {
                    b.HasOne("Buildings.Infrastructure.Data.Entities.Account.UserAccountInfo", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Forum.BlogComment", b =>
                {
                    b.Navigation("ChildComments");
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.Forum.BlogPost", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
