// <auto-generated />
using System;
using System.Text.Json;
using Buildings.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Buildings.Migrations
{
    [DbContext(typeof(BuildingDbContext))]
    [Migration("20260506003824_AddUserMoreInfo")]
    partial class AddUserMoreInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.AccountTokens", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Hash")
                        .HasName("PK_AccountTokens_UserId");

                    b.ToTable("AccountTokens", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.AccountUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordSaltHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId")
                        .HasName("PK_AccountUser_UserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AccountUser_CreatedAt");

                    b.HasIndex("UpdateAt")
                        .HasDatabaseName("IX_AccountUser_UpdateAt");

                    b.HasIndex("Email", "DeleteAt")
                        .IsUnique()
                        .HasDatabaseName("IX_AccountUser_Email");

                    b.ToTable("AccountUser", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.BuildingArticleData", b =>
                {
                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dynasties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provinces")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("Seo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArticleId")
                        .HasName("PK_BuildingArticleData_ArticleId");

                    b.HasIndex("Categories")
                        .HasDatabaseName("IX_BuildingArticleData_Categories");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Categories"), "GIN");

                    b.HasIndex("Dynasties")
                        .HasDatabaseName("IX_BuildingArticleData_Dynasties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Dynasties"), "GIN");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_BuildingArticleData_Hash");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("IX_BuildingArticleData_Path");

                    b.HasIndex("Provinces")
                        .HasDatabaseName("IX_BuildingArticleData_Provinces");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Provinces"), "GIN");

                    b.ToTable("BuildingArticleData", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.FriendRelation", b =>
                {
                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FromUserId", "TargetUserId")
                        .HasName("PK_FriendRelation_FromUserId_TargetUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FriendRelation_CreatedAt");

                    b.HasIndex("FromUserId", "TargetUserId", "DeleteAt")
                        .IsUnique()
                        .HasDatabaseName("IX_FriendRelation_DeleteAt");

                    b.ToTable("FriendRelation", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.FriendRequest", b =>
                {
                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("FromUserId", "TargetUserId")
                        .HasName("PK_FriendRequest_FromUserId_TargetUserId");

                    b.ToTable("FriendRequest", (string)null);
                });

            modelBuilder.Entity("Buildings.Infrastructure.Data.Entities.UserInfo", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("PK_UserInfo_UserId");

                    b.HasIndex("Location")
                        .HasDatabaseName("IX_UserInfo_Location");

                    b.HasIndex("Tags")
                        .HasDatabaseName("IX_UserInfo_Tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "GIN");

                    b.ToTable("UserInfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
